#!/usr/bin/env python

import json
import sys
import os
import logging
import collatinus
import re

logger = logging.getLogger('root')
FORMAT = "<%(filename)s:%(lineno)s> in %(funcName)s ] %(message)s"
logging.basicConfig(format=FORMAT)
logger.setLevel(logging.INFO)
rgx_letters = re.compile('\w')

def main():
    if len(sys.argv) < 2:
        usage()

    fn = sys.argv[1]

    testfile = fn

    try:
        with open(testfile,mode='r', encoding='utf-8') as fh:
            contents = fh.read()
    except Exception as e:
        logger.error("Couldn't read files: %s", e)
        exit(1)

    cl = collatinus.clean.Cleaner()

    try:
        sents = cl.tokenize_sentences(contents)

    except Exception as e:
        logger.error(" Failed to clean %s - %s" % (testfile, e))
        logger.exception(e)
        exit(1)

    print('\n'.join(sents),end='')

if __name__ == '__main__':
    main()